org: flashcoffee
app: serverless-nest
service: todos-service

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions: ${file(serverless-function.yml)}

resources:
  - Resources: ${file(serverless-resources.yml)}
