org: flashcoffee
app: serverless-nest
service: todos-service

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  api:
    handler: dist/serverless/handlers/api.handler
    events:
      - http:
          method: any
          path: '/todos'
          cors: true
      - http:
          method: any
          path: '/todos/{proxy+}'
          cors: true
      - http:
          method: any
          path: '/users'
          cors: true
      - http:
          method: any
          path: '/users/{proxy+}'
          cors: true

  hello:
    handler: dist/serverless/handlers/hello.handler
    events:
      - http: 
          method: get
          path: /hello-service/hello
